language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - PYTHON_VER=2.7
    - PYTHON_VER=3.4
    - PYTHON_VER=3.5
    - PYTHON_VER=3.6


install:
    # Install Miniconda.
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      source $HOME/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda info

    - conda create -n test --yes --quiet python=${PYTHON_VER} setuptools pip cython sphinx pari flake8
    - source activate test

script:
  - make -j4 install
  - make -j4 check-all distcheck
